bases/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from bases.views import *

app_name = "config"

urlpatterns = [
    path('',Home.as_view(),name='home'),
    path('login/',auth_views.LoginView.as_view(template_name='bases/login.html'),
        name='login'),
    path('logout/',
         auth_views.LogoutView.as_view(template_name='bases/login.html'),
         name='logout'),
    
    path('users/lists',UserList.as_view(),name="users_list"),
    path('users/add',user_admin,name="user_add"),
    path('users/modify/<int:pk>',user_admin,name="user_modify"),
    path('users/groups/list',UserGroupList.as_view(),name="user_groups_list"),
    path('users/groups/add',user_groups_admin,name="user_groups_new"),
    path('users/groups/modify/<int:pk>',user_groups_admin,name="user_groups_modify"),
    path('users/groups/delete/<int:pk>',user_group_delete,name="user_groups_delete"),
    
    path('users/groups/permission/<int:id_grp>/<int:id_perm>',user_group_permission,name="user_groups_permission"),
    path('users/groups/admin/<int:id_usr>/<int:id_grp>',user_group_add, \
        name="user_groups_admin"),

    path('catalogos/categorias',
	 Home.as_view(),
	 name='categorias'),
    path('catalogos/subcategorias',
        Home.as_view(),
        name='subcategorias'),
    path('movimientos/compras',
        Home.as_view(),
        name='compras'),
]

proyecto/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('',include(('bases.urls','bases'), namespace='bases')),
    path('admin/', admin.site.urls),
]

bases/models.py
from django.db import models
from django.utils import timezone
from django.utils.http import urlquote
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin


from .managers import UsuarioManager

class Usuario(AbstractBaseUser,PermissionsMixin):
    email = models.EmailField(_('direccion email'), max_length=254, unique=True)
    first_name = models.CharField(_('nombres'), max_length=30, blank=True)
    last_name = models.CharField(_('apellidos'), max_length=30, blank=True)
    is_staff = models.BooleanField(_('es staff'), default=False,
        help_text=_('Indica si el usuario puede iniciar sesión en admin '))
    is_active = models.BooleanField(_('activo'), default=True,
        help_text=_('Designa si este usuario debe ser tratado como activo'
                    'Deseleccione esto en lugar de eliminar cuentas.'))
    date_joined = models.DateTimeField(_('fecha registro'), default=timezone.now)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UsuarioManager()

    class Meta:
        verbose_name = _('usuario')
        verbose_name_plural = _('usuarios')

    def get_absolute_url(self):
        return "/users/%s" % urlquote(self.email)
    
    def get_full_name(self):
        full_name = "%s %s" % (self.first_name,self.last_name)
        return full_name.strip()
    
    def get_short_name(self):
        return self.first_name

bases/forms.py
from django.contrib.auth import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.db import models
from django.forms import fields
from django import forms
from django.forms.widgets import PasswordInput

from .models import Usuario

class UsuarioCreationForm(UserCreationForm):
    def __init__(self,*args,**kwargs):
        super(UsuarioCreationForm,self).__init__(*args,**kwargs)

    class Meta:
        model = Usuario
        fields = ("email",)


class UsuarioChangeForm(UserChangeForm):
    def __init__(self,*args,**kwargs):
        super(UsuarioChangeForm,self).__init__(*args,**kwargs)

    class Meta:
        model = Usuario
        fields = '__all__'

class Userform(forms.ModelForm):
    password = forms.CharField(widget=PasswordInput)
    
    class Meta:
        model = Usuario
        fields = ['email','first_name','last_name','password']
        widget = {'email': forms.EmailInput,
                   'password': forms.PasswordInput }

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

bases/views.py
from re import U
from django import http
from django.db.models.query import RawQuerySet
from django.http import request
from django.http.response import Http404, HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import *
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import Group, Permission
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Q
from django.contrib import messages

from .models import Usuario
from .forms import Userform

class Home(LoginRequiredMixin,TemplateView):
    template_name = 'bases/home.html'
    login_url = 'config:login'

    
class UserList(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    template_name = "bases/users_list.html"
    login_url = 'config:login'
    model = Usuario
    permission_required = 'bases:view_usuario'
    context_object_name = 'obj'

@login_required(login_url='config:login')
@permission_required('bases.change_ususario', login_url='config:home')
def user_admin(request,pk=None):
    template_name = "bases/users_add.html"
    context = {}
    form = None
    obj = None

    if request.method == "GET":
        if not pk:
            form = Userform(instance = None )
        else:
            obj = Usuario.objects.filter(id=pk).first()
            form = Userform(instance = obj)
        context["form"] = form
        context["obj"] = obj

        grupos_usuarios = None
        grupos = None
        if obj:
            grupos_usuarios = obj.groups.all()
            grupos = Group.objects.filter(~Q(id__in=obj.groups.values('id')))
        
        context["grupos_usuario"]=grupos_usuarios
        context["grupos"]=grupos
    
    if request.method == "POST":
        data = request.POST
        e = data.get("email")
        fn = data.get("first_name")
        ln = data.get("last_name")
        p = data.get("password")

        if pk:
            obj = Usuario.objects.filter(id=pk).first()
            if not obj:
                print("Error Usuario No Existe")
            else:
                obj.email = e
                obj.first_name = fn
                obj.last_name = ln
                obj.password = make_password(p)
                obj.save()
        else:
            obj = Usuario.objects.create_user(
                email = e,
                password = p,
                first_name = fn,
                last_name = ln
            )
            print(obj.email,obj.password)
        return redirect('config:users_list')
    
    return render(request,template_name,context)


class UserGroupList(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    template_name = "bases/users_group_list.html"
    login_url = 'config:login'
    model = Group
    permission_required = 'bases:view_usuario'
    context_object_name = 'obj'

@login_required(login_url='config:login')
@permission_required('bases.change_usuario', login_url='bases:login')
def user_groups_admin(request,pk=None):
    template_name = 'bases/users_group_add.html'
    context = {}

    obj = Group.objects.filter(id = pk).first()
    context["obj"] = obj
    permisos = {}
    permisos_grupo = {}
    context["permisos"] = permisos
    context["permisos_grupo"] = permisos_grupo

    if obj:
        permisos_grupo = obj.permissions.all()
        context["permisos_grupo"] = permisos_grupo

        permisos = Permission.objects.filter(~Q(group=obj))
        context["permisos"] = permisos

    # print(permisos)
    # print(permisos_grupo)
    if request.method == "POST":
        name = request.POST.get("name")
        grp = Group.objects.filter(name=name).first()

        if grp and grp.id != pk:
            print("Grupo ya existe, no puede volver a crearlo")
            messages.error(request,"Grupo ya existe, no puede volver a crearlo")
            return redirect("config:user_groups_new")
        
        if not grp and pk != None:
            # Grupo Existe, se está cambiando el Nombre
            grp = Group.objects.filter(id=pk).first()
            grp.name = name
        elif not grp and pk == None:
            grp = Group(name=name)
        else:
            ...
        
        grp.save()
        messages.success(request, "Registro Guardado Satisfactoriamente")
        return redirect("config:user_groups_modify", grp.id)
    return render(request,template_name,context)


@login_required(login_url='config:login')
@permission_required('bases.change_usuario', login_url='bases:login')
def user_group_delete(request,pk):
    if request.method == "POST":
        grp = Group.objects.filter(id=pk).first()

        if not grp:
            print("Grupo No Existe")
        else:
            grp.delete()
        
        messages.success(request,"Registro Borrado Satisfactoriamente")
        return HttpResponse("OK")


@login_required(login_url='config:login')
@permission_required('bases.change_usuario', login_url='bases:login')
def user_group_permission(request,id_grp,id_perm):
    if request.method == "POST":
        grp = Group.objects.filter(id = id_grp).first()

        if not grp:
            messages.error(request,"Grupo No Existe")
            return HttpResponse("Grupo No Existe")
        
        accion = request.POST.get("accion")
        perm = Permission.objects.filter(id=id_perm).first()
        if not perm:
            messages.error(request,"Permiso no existe")
            return HttpResponse("Permiso No Existe")
        
        if accion == "ADD":
            grp.permissions.add(perm)
            messages.success(request,"Permiso Agregado")
        elif accion == "DEL":
            grp.permissions.remove(perm)
            messages.success(request,"Permiso Eliminado")
        else:
            messages.error(request,"Accion no Reconocida")
            return HttpResponse("Accion No Reconocida")

        return HttpResponse("OK")
    return Http404("Método no Reconocido")


@login_required(login_url='config:login')
@permission_required('bases.change_usuario', login_url='bases:login')
def user_group_add(request,id_usr,id_grp):
    if request.method == "POST":
        usr =Usuario.objects.filter(id=id_usr).first()
        if not usr:
            return HttpResponse("Usuario NO Existe")
        
        accion = request.POST.get("accion")
        grp = Group.objects.filter(id=id_grp).first()

        if not grp:
            return HttpResponse("Grupo No Existe")
        
        if accion=="ADD":
            usr.groups.add(grp)
        elif accion=="DEL":
            usr.groups.remove(grp)
        else:
            return HttpResponse("Acción no Reconocida")
        
        return HttpResponse("OK")
    
    return HttpResponse("Error Método no Reconocido")

bases/templates/bases/home.html
{% extends 'base/index.html' %}

{% block content_wrapper %}{% endblock %}
{% block content %}
{% endblock%}

bases/templates/bases/login.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Sistema de Compra y Facturación con Django 3.2 x Daniel Bojorge</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %ç">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <!-- /.login-logo -->
        <div class="card card-outline card-primary">
          <div class="card-header text-center">
            <div class="h1"><b>DEBS</b> Consultores</div>
          </div>
          <div class="card-body">
            <p class="login-box-msg">Bienvenido a la APP del Curso<br>
              <strong>Sistema de Compra y Facturación con Django 3.2</strong><br> <small>Ingresa tus Datos</small></p>
      
            <form  method="post">
              {% csrf_token %}
      
              <small class="text-danger">
                {% if messages %}
                {% for m in messages%}
                  {{m}} <br>
                {% endfor %}
              {% endif %}
                {% if form.errors %}
                    {% for field in form %}
                        {% if field.errors %}
                            {% for error in field.errors %}
                                {{ error|escape }} ({{field.name}})<br>
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                
                    {% if form.non_field_errors%}
                        {% for error in form.non_field_errors %}
                            {{ error|escape }} <br>
                        {% endfor %}
                    {% endif %}
                {% endif %}
            </small>
              <div class="input-group mb-3">
                <input type="email" name="username" id="id_username" autofocus="" class="form-control" placeholder="Email">
                <div class="input-group-append">
                  <div class="input-group-text">
                    <span class="fas fa-envelope"></span>
                  </div>
                </div>
              </div>
              <div class="input-group mb-3">
                <input type="password" class="form-control" name="password" id="id_password" placeholder="Password">
                <div class="input-group-append">
                  <div class="input-group-text">
                    <span class="fas fa-lock"></span>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-8">
                </div>
                <!-- /.col -->
                <div class="col-4">
                  <button type="submit" class="btn btn-primary btn-block">Login</button>
                </div>
                <!-- /.col -->
              </div>
            </form>
      
            
            <!-- /.social-auth-links -->
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
      <!-- /.login-box -->
<!-- /.login-box -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
</body>
</html>

bases/templates/bases/users_add.html
{% extends 'base/index.html' %}

{% block content_wrapper %}
<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">Agregar Usuarios/Permisos</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">Inicio</a></li>
            <li class="breadcrumb-item active">Agregar Usuarios/Permisos</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
{% endblock %}
{% block content %}
<!-- ./row -->
<div class="row">
    <div class="col-12 col-sm-12">
      <div class="card card-primary card-tabs">
        <div class="card-header p-0 pt-1">
          <ul class="nav nav-tabs" id="custom-tabs-one-tab" role="tablist">
            <li class="nav-item">
              <a class="nav-link active" id="custom-tabs-one-home-tab" data-toggle="pill" href="#custom-tabs-one-home" role="tab" aria-controls="custom-tabs-one-home" aria-selected="true">
                {% if obj %}Editar{%else%}Agregar{%endif%}
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="custom-tabs-one-profile-tab" data-toggle="pill" href="#custom-tabs-one-profile" role="tab" aria-controls="custom-tabs-one-profile" aria-selected="false">Grupos</a>
            </li>
          </ul>
        </div>
        <div class="card-body">
          <div class="tab-content" id="custom-tabs-one-tabContent">
            <div class="tab-pane fade show active" id="custom-tabs-one-home" role="tabpanel" aria-labelledby="custom-tabs-one-home-tab">
              <form method="POST" class="form-group">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn bg-danger btn-app"><i class="fas fa-save"></i> Guardar </button>
                <button type="reset" class="btn bg-info btn-app"><i class="fas fa-window-close"></i> Cancelar</button>
                <a href="{% url 'config:users_list'%}" class="btn btn-app bg-warning"><i class="far fa-hand-point-left"></i> Regresar</a>
            </form>
            </div>
            <div class="tab-pane fade" id="custom-tabs-one-profile" role="tabpanel" aria-labelledby="custom-tabs-one-profile-tab">
               <!-- Grupos:{{grupos}} <br> Grupos de usuario: {{grupos_usuarios}} -->
               {% if obj %}
               <div class="row">
                 <div class="col-6">
                  <div class="card">
                    <div class="card-header">
                    Grupos del Usuario {{obj}}
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                    <table id="tblGrp" class="table table-bordered table-striped">
                      <thead>
                      <tr>
                      <th>Id</th>
                      <th>Nombre</th>
                      <th>Acciones</th>
                      </tr>
                      </thead>
                      <tbody>
                        {% for item in grupos_usuario%}
                        <tr>
                          <td>{{item.id}}</td>
                          <td>{{item.name}}</td>
                          <td>
                            <a href="#" class="btn btn-sm text-success"
                            onclick="permiso('{{item.id}}','DEL')"
                            ><i class="far fa-trash-alt"></i></a>
                          </td>
                        </tr>
                        {%endfor%}
                
                      </tbody>
                    </table>
                    </div>
                    <!-- /.card-body -->
                  </div>
                  <!-- /.card -->
                 </div>
                 <div class="col-6">
                  <div class="card">
                    <div class="card-header">
                      Todos los Grupos
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                      <table class="table table-bordered table-striped">
                      <thead>
                      <tr>
                        <th>Id</th>
                        <th>Nombre</th>
                        <th>Acciones</th>
                      </tr>
                      </thead>
                      <tbody>
                        {% for item in grupos%}
                        <tr>
                          <td>{{item.id}}</td>
                          <td>{{item.name}}</td>
                          <td>
                            <a href="#" class="btn btn-sm text-success"
                            onclick="permiso('{{item.id}}','ADD')"
                            ><i class="fas fa-plus"></i></a>
                          </td>
                        </tr>
                        {%endfor%}
                  
                      </tbody>
                      </table>
                    </div>
                    <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                 </div>
               </div>
               {% endif %}

            </div>
          </div>
        </div>
        <!-- /.card -->
      </div>
    </div>
  </div>
{% endblock%}

{% block js %}
<script>
  function permiso(id,accion){
    // alert(id)
    // alert(accion)
    var url = "/users/groups/admin/{{obj.id}}/" + id
    var token = '{{csrf_token}}'
    var data = {"accion":accion}
    $.ajax({
      headers : {"X-CSRFToken": token},
      type:"POST",
      url:url,
      data:data,
      success: function(r){
        if(r=="OK"){
          location.reload(true)
        }else{
          Swal.fire("Error Inesperado tratando de borrar registro " + r);
        }
      },
      error: function(jqXHR, textStatus, errorThrow){
        console.log(textStatus, errorThrow);
        Swal.fire(errorThrow,"",'red');
      }
    })

  }
</script>
{% endblock js%}

bases/templates/bases/users_group_add.html
{% extends 'base/index.html' %}

{% block content_wrapper %}
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        {% if obj %} Editar {% else %} Crear {% endif %} Grupo de Usuario
      </div>
      <div class="card-body">
        <form method="POST" class="form-group">
          {% csrf_token %}
          <div class="form-group">
            <label for="exampleInputEmail1">Nombre</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Nombre Grupo"
            value="{{obj.name}}">
          </div>
          <button type="submit" class="btn bg-danger btn-app"><i class="fas fa-save"></i> Guardar</button>
          <button type="reset" class="btn bg-info btn-app"><i class="fas fa-window-close"></i> Cancelar</button>
          <a href="{% url 'config:user_groups_list'%}" class="btn btn-app bg-warning"><i class="far fa-hand-point-left"></i> Regresar</a>
      </form>
      </div>
    </div>
  </div>
</div>
{% if obj %}
<div class="row">
  <div class="col-6">
    <div class="card">
      <div class="card-header">
        Permisos del Grupo {{obj}}
      </div>
      <!-- /.card-header -->
      <div class="card-body">
        <table id="tblGrp" class="table table-bordered table-striped">
          <thead>
          <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Acciones</th>
          </tr>
          </thead>
          <tbody>
              {% for item in permisos_grupo%}
              <tr>
                  <td>{{item.id}}</td>
                  <td>{{item.name}}</td>
                  <td>
                      <a href="#" class="btn btn-sm text-success"
                      onclick="permiso('{{item.id}}','DEL')"
                      ><i class="far fa-trash-alt"></i></a>
                  </td>
              </tr>
              {%endfor%}

          </tbody>
        </table>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->
  </div>
  <div class="col-6">
    <div class="card">
      <div class="card-header">
        Todos los Permisos
      </div>
      <!-- /.card-header -->
      <div class="card-body">
        <table id="tbl" class="table table-bordered table-striped">
          <thead>
          <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Acciones</th>
          </tr>
          </thead>
          <tbody>
              {% for item in permisos%}
              <tr>
                  <td>{{item.id}}</td>
                  <td>{{item.name}}</td>
                  <td>
                      <a href="#" class="btn btn-sm text-success"
                      onclick="permiso('{{item.id}}','ADD')"
                      ><i class="fas fa-plus"></i></a>
                  </td>
              </tr>
              {%endfor%}

          </tbody>
        </table>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->
  </div>
</div>
{% endif %}
{% endblock%}

{% block js%}
<script>
  function permiso(id,accion){
    var url = "/users/groups/permission/{{obj.id}}/" + id
    var token = '{{csrf_token}}'
    var data = {"accion":accion}

    console.log(url,token,data)

    $.ajax({
      headers : {"X-CSRFToken": token},
      type:"POST",
      url:url,
      data:data,
      success: function(response){
        if(response==="OK"){
          location.reload(true)
        }else{
          Swal.fire(response,"","red")
        }
      },
      error: function(jqXHR, textStatus, errorThrow){
        console.log(textStatus, errorThrow);
        Swal.fire(errorThrow,"",'red');
      }
    })
  }
</script>
{% endblock %}

bases/templates/bases/users_group_list.html
{% extends 'base/index.html' %}

{% block content_wrapper %}
<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">Listado de Grupos</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item active">Listado de Grupos</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
              <!-- <h3 class="card-title">DataTable with default features</h3> -->
              <a href="{% url 'config:user_groups_new' %}" class="btn btn-app bg-info"><i class="fas fa-plus-circle"></i></a>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="tbl" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Id</th>
                  <th>Nombre</th>
                  <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                    {% for item in obj%}
                    <tr>
                        <td>{{item.id}}</td>
                        <td>{{item.name}}</td>
                        <td>
                            <a href="{% url 'config:user_groups_modify'  item.id %}" class="btn btn-sm text-success"><i class="fa fa-edit"></i></a>
                            <button type="button" class="btn btn-sm text-danger"
                            onclick='return abrir_borrar("{{item.name}}","{% url 'config:user_groups_delete' item.id%}")'><i class="far fa-trash-alt"></i></button>
                        </td>
                    </tr>
                    {%endfor%}

                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
    </div>
</div>
{% endblock%}

bases/templates/bases/users_list.html
{% extends 'base/index.html' %}

{% block content_wrapper %}
<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">Listado de Usuarios</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item active">Listado de Usuarios</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
              <!-- <h3 class="card-title">DataTable with default features</h3> -->
              <a href="{% url 'config:user_add' %}" class="btn btn-app bg-info"><i class="fas fa-user-plus"></i></a>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="tbl" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Id</th>
                  <th>EMail</th>
                  <th>Name</th>
                  <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                    {% for i in obj %}
                <tr>
                  <td>{{i.id}}</td>
                  <td>{{i.email}}</td>
                  <td>{{i.get_full_name}}</td>
                  <td>
                    {% if not i.is_staff %}
                    <a href="{% url 'config:user_modify' i.id %}" class="btn btn-sm text-success"><i class="fa fa-edit"></i></a>
                    {% elif user.is_staff %}
                    <a href="{% url 'config:user_modify' i.id %}" class="btn btn-sm text-success"><i class="fa fa-edit"></i></a>
                    {% endif %}
                  </td>
                </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
    </div>
</div>
{% endblock%}